const apiUrls = {
  fundListApi: 'Fund/FundDefinitions/All',
  fundGetById: 'Fund/FundDefinitions/',
  fundCreateApi: 'Fund/FundDefinitions',
  fundDeleteApi: 'Fund/FundDefinitions',
  fundUpdateApi: 'Fund/FundDefinitions/',
  issuerCreateApi: 'Fund/IssuerCorporations',
  issuerListApi: 'Fund/IssuerCorporations/All',
  fundOrderListApi: 'Fund/FundOrders/All',
  fundOrderGetById: 'Fund/FundOrders/',
  fundOrderCreateApi: 'Fund/FundOrders',
  fundOrderDeleteApi: 'Fund/FundOrders',
  fundOrderUpdateApi: 'Fund/FundOrders/',
  fundOrderCancellingApi: 'Fund/FundOrders/CancellingFundOrder/',
  fundOrderListByAccountNumber: 'Fund/FundOrders/ByParameters',
  fundAndPriceListApi: 'Fund/FundDefinitions/DailyFunds',
  fundBuyingCreateApi: 'Fund/FundDefinitions/Buying',
  fundSellingCreateApi: 'Fund/FundDefinitions/Selling',
  fundSecurityPriceById: 'Fund/SecurityPrices/',
  fundPriceByParameters: 'Fund/SecurityPrices/ByParameters',
  customerPortfolioByAccountNumber: 'Fund/FundDefinitions/CustomerPortfolioByAccountNumber',
  createSecPrice: 'Fund/SecurityPrices',
  fundPortfolioListApi: 'Fund/FundDefinitions/GetFundSecurityPriceList',
  fundMergeApi: 'Fund/FundDefinitions/MergeFunds',
  fundSecurityListByWorkGroup: 'Fund/FundDefinitions/GetFundSecuritiesByWorkGroupId',
  fundOrderListByParameters: 'Fund/FundOrders/ByParameters',
  fundBuyingCreateApi: 'Fund/FundDefinitions/Buying',
  fundSellingCreateApi: 'Fund/FundDefinitions/Selling',
  fundSecurityPriceById: 'Fund/SecurityPrices/',
  fundPriceByParameters: 'Fund/SecurityPrices/ByParameters',
  customerPortfolioByAccountNumber: 'Fund/FundDefinitions/CustomerPortfolioByAccountNumber',
  createSecPrice: 'Fund/SecurityPrices',
  fundBuyingCreateApi:'Fund/FundDefinitions/Buying',
  fundSellingCreateApi:'Fund/FundDefinitions/Selling',
  fundSecurityPriceById:'Fund/SecurityPrices/',
  fundPriceByParameters:'Fund/SecurityPrices/ByParameters',
  customerPortfolioByAccountNumber:'Fund/FundDefinitions/CustomerPortfolioByAccountNumber',
  createSecPrice:'Fund/SecurityPrices',
  fundPortfolioListApi : 'Fund/FundDefinitions/GetFundSecurityPriceList',
  fundMergeApi : 'Fund/FundDefinitions/MergeFunds',
  fundSecurityListByWorkGroup : 'Fund/FundDefinitions/GetFundSecuritiesByWorkGroupId',
  fundOrderListByParameters : 'Fund/FundOrders/ByParameters',
  fundSecurityPriceChartByDatePartApi: 'Fund/SecurityPrices/ByDatePart',
  fundGetLastSecPrice : 'Fund/SecurityPrices/LastSecPriceByFundId',
  fundListByParameters : 'Fund/FundDefinitions/ByParameters',
  checkProcessDocuments :'Dms/ProcessDocumentInstances'
};

export { apiUrls };
